### PR TITLE
feat: show toast messages when error

### PR DESCRIPTION
**Pull request by aakash19here**
The reason why I had to change the styles is due to the toaster. For some reasons the styles for loader are getting updated due to it. You can check dev tools. The current workaround is to force the styles using !important tag

### CODE REVIEW

**Comment by aakash19here** [comment]
It's my formatter I guess due to which there are these many changes

**Comment by aakash19here** [comment]
MB , the build was failing cause of packages , fixed it in the latest commit

**Comment by Dhravya** [comment]
I cannot merge this pull request, because of the formatting. Can you send another PR with just the changes?

**Comment by aakash19here** [comment]
> I cannot merge this pull request, because of the formatting. Can you send another PR with just the changes?

sure

**Pull request closed without merging**
