### PR TITLE
added optimitic dump post

### PR DESCRIPTION
**Pull request by kenneropia**
this fixes [#12 ](https://github.com/Dhravya/dump.place/issues/12)

@Dhravya

### CODE REVIEW

**Comment by Dhravya** [comment]
Amazing work, I'm curious as to how you implemented it, can you document it in short? I see you used a global state, would love to know more about it

**Comment by kenneropia** [comment]
Thanks for the compliment. 

First the state management lib is called zustard, I used it in place of the Context API, because it is more reliable, easier to use and it is tiny. I used a global state, because as you know it, the list of dumps is fully SSRed(with no hydration), which leave out the type of interaction, we needed to introduce a more simpler optimistic update(like just merging the dump content in the form with the list of dumps in something like usestate, if we were doing client), so I created a new components called optimistic dump, which will show the uploading dumps to the user by referring the global state(powered by zustard). The component will only render, if there is a dump in the state, which of course will be cleared just between when the form has been submitted and immediately when the server action revalidates the route. I hope this was clear enough!

**Comment by anuragts** [comment]
> Thanks for the compliment.
> 
> First the state management lib is called zustard, I used it in place of the Context API, because it is more reliable, easier to use and it is tiny. I used a global state, because as you know it, the list of dumps is fully SSRed(with no hydration), which leave out the type of interaction, we needed to introduce a more simpler optimistic update(like just merging the dump content in the form with the list of dumps in something like usestate, if we were doing client), so I created a new components called optimistic dump, which will show the uploading dumps to the user by referring the global state(powered by zustard). The component will only render, if there is a dump in the state, which of course will be cleared just between when the form has been submitted and immediately when the server action revalidates the route. I hope this was clear enough!

good stuff

**Comment by Dhravya** [comment]
LGTM. Great work man <3

**Pull request merged**
