### PR TITLE
move ADMIN_EMAIL to .env

### LINKED ISSUE #8: Email is hardcode
The admin email is currently hardcoded in the server actions file. While this may not necessarily imply vulnerability to attacks, it is advisable to consider moving it to the .env folder, especially in light of the recent DDOS attack.

image

### PR DESCRIPTION
**Pull request by anuragts**
resolves #8

### CODE REVIEW

**Review by Dhravya — CHANGES_REQUESTED** [review]
in `src/env.js`, you neeed to make the change at two places-  it's only done once

**Comment by anuragts** [comment]
Updated the code as requested @Dhravya

**Review by Dhravya — APPROVED** [review]

**Review by Dhravya — CHANGES_REQUESTED** [review]
There's more occurrences of my email in `src/app/admin/page.tsx`, replace those too

**Comment by anuragts** [comment]
> There's more occurrences of my email in `src/app/admin/page.tsx`, replace those too

lmao haven't read whole code , will do everywhere

**Comment by anuragts** [comment]
Updated the code as requested @Dhravya

**Pull request merged**
