### PR TITLE
Render markdown properly and UI update

### PR DESCRIPTION
**Pull request by kenneropia**
This fixed issues #16 , kindly review.
I added:
1. a preview button to review created mark down content before submitting.
2. fixed the issue was tailwind not using the proper css styles for the markdown content.

### CODE REVIEW

**Comment by kenneropia** [comment]
Hello @Dhravya, check this out when you are free please.

**Comment by Dhravya** [comment]
looks really good. could you please just remove vscode settings file?

**Comment by Dhravya** [comment]
great work btw. amazing stuff

**Comment by Dhravya** [comment]
images with rounded borders?

**Comment by kenneropia** [comment]
I have removed the vscode stuff. what do you means by "images with rounded borders?"

**Comment by Dhravya** [comment]
Markdown has images, can you make the image border rounded-md? check out https://dump.place/@yash

**Comment by kenneropia** [comment]
On it 🫡

**Comment by kenneropia** [comment]
Is this okay? this is currently a rounded-md size, the image is in the bottom left, cropped for focus.
image

**Pull request merged**
