### PR TITLE
feat: add rate limit w/ redis :zap:

### PR DESCRIPTION
**Pull request by aakash19here**

### CODE REVIEW

**Comment by aakash19here** [comment]
To see it in action in the preview add the keys to the preview deployment too

**Comment by aakash19here** [comment]
Hey @Dhravya , did this work dor you ?

**Comment by Dhravya** [comment]
Yes, it did! Sorry for the delay.

**Review by Dhravya — APPROVED** [review]

**Comment by Dhravya** [comment]
GG @aakash19here, thanks for the contribution!

**Pull request merged**
