### PR TITLE
featix: ui fix and new look with animation

### PR DESCRIPTION
**Pull request by Kinfe123**
image
new looking :fire:

### CODE REVIEW

**Comment by Dhravya** [comment]
Hi! Can you pls add `@typescript-eslint/no-inferrable-types : off` to the eslint rules file?

**Comment by Dhravya** [comment]
Also, I'm concerned this UX improvements PR will conflict with this one, but those improvements are pretty important https://github.com/Dhravya/dump.place/pull/14

**Comment by yxshv** [comment]
> image new looking 🔥

i think thats supposed to "noise proof" 😂

**Comment by Kinfe123** [comment]
okay cool i am on it

**Comment by Kinfe123** [comment]
> > image new looking 🔥
> 
> i think thats supposed to "noise proof" 😂

Yeep :laughing:

**Comment by Kinfe123** [comment]
It is just easy handling the conflicts or i can handle that for you if you get stucked

**Comment by Kinfe123** [comment]
Up until now , it doesnot have a conflict but once you have merged his code i will be checking out and pulling from your main . No worries

**Comment by Dhravya** [comment]
Hmm, something's wrong in the deployed URL, it looks like this 
image

**Comment by Kinfe123** [comment]
wait i have not checked up on the post it is just wrapping them with max-w-3xl or 2xl kind of thing

**Comment by Dhravya** [comment]
```

Failed to compile.
--
15:04:34.227 |  
15:04:34.228 | ./src/components/dump.tsx
15:04:34.228 | Error:
15:04:34.228 | x Merge conflict marker encountered.
15:04:34.229 | ,-[/vercel/path0/src/components/dump.tsx:7:1]
15:04:34.229 | 7 \|
15:04:34.229 | 8 \| export function Dump({ dump }: { dump: Dumps }) {
15:04:34.229 | 9 \|   return (
15:04:34.229 | 10 \| <<<<<<< Updated upstream
15:04:34.230 | : ^^^^^^^
15:04:34.230 | 11 \|     <div className="rounded-2xl border p-4 dark:border-white/20 transition-[border-color] dark:hover:border-white/50">
15:04:34.230 | 12 \| =======
15:04:34.230 | 13 \|     <div className=" p-4 flex-col justify-start items-start gap-2 bg-gradient-to-tr from-purple-400/10  via-gray-500/5 to-transparent border-black/50 dark:border-white/20 border-[0.1px] shadow-zinc-500  dark:shadow-purple-400  rounded-2xl px-7 py-5 transition-[border-color] dark:hover:border-white/50">
15:04:34.230 | `----
15:04:34.231 |  
15:04:34.231 | x Expression expected
15:04:34.231 | ,-[/vercel/path0/src/components/dump.tsx:8:1]
15:04:34.231 | 8 \| export function Dump({ dump }: { dump: Dumps }) {
15:04:34.231 | 9 \|   return (
15:04:34.232 | 10 \| <<<<<<< Updated upstream
15:04:34.232 | 11 \|     <div className="rounded-2xl border p-4 dark:border-white/20 transition-[border-color] dark:hover:border-white/50">
15:04:34.232 | :                                                                                                                      ^

```

No rush, pls test your code :)

**Comment by Kinfe123** [comment]
it is not mine.. i have not pulled anything yet

**Comment by Kinfe123** [comment]
image

**Comment by Dhravya** [comment]
that's weird, it was from the auto deployment, let's try that again

**Comment by Kinfe123** [comment]
i can send u my deployment if u want to easily track

**Comment by Dhravya** [comment]
Would be helpful! here's what the current deployment looks - the hero isn't visible
image

**Comment by Kinfe123** [comment]
oh.. you do have a mobile audience i will fix it later man

**Comment by Dhravya** [comment]
Yeah, all design is mobile first

**Comment by Dhravya** [comment]
Holy shit this is fire.

**Comment by Dhravya** [comment]
@Kinfe123 Thanks a lot!!! Great design.

**Comment by Kinfe123** [comment]
No worries , i will be iterating on polishing the design

**Pull request merged**
