### PR TITLE
feat: show toasts when error

### PR DESCRIPTION
**Pull request by aakash19here**

### CODE REVIEW

**Comment by aakash19here** [comment]
man what is your build command ?

**Comment by aakash19here** [comment]
Your readme suggests to install packages w/ npm , and still has pnpm lock file. if you want to use pnpm , package-lock file needs to be removed

**Comment by Dhravya** [comment]
My bad. yes, I use pnpm. really sorry

**Comment by aakash19here** [comment]
> My bad. yes, I use pnpm. really sorry

no worries mate

**Comment by aakash19here** [comment]
Didn't commit the changes in the dumpform  ,LMAO sorry

**Comment by Dhravya** [comment]
GG @aakash19here, merged and deployed. great work!

**Pull request merged**
